name: EC2 Deploy

on:
  push:
    branches:
      - "*"
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.ref }}
          
      - name: Create SSH
        run: |
          bash -c 'mkdir -p ~/.ssh/ && echo "${{ secrets.MY_SECRET_SSH_KEY }}" > ~/.ssh/secretKey.pem && chmod 400 ~/.ssh/secretKey.pem'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Pull Docker image
        run: |
          docker pull mesgna/london-mini-guide:latest
          
      - name: Connect to EC2 and Run Container
        run: |
          ssh -i ~/.ssh/secretKey.pem -o StrictHostKeyChecking=no ubuntu@ec2-35-176-144-41.eu-west-2.compute.amazonaws.com <<'EOF'
            # Navigate to the project directory
            cd ~/project-2/london-mini-guide
  
            # Stop and remove existing container (handle potential errors)
            docker stop london-mini-guide || true
            docker rm london-mini-guide || true
  
            # Run the new container with environment variables (consider secrets management)
            docker run -d -p 5100:5000 --name london-mini-guide mesgna/london-mini-guide:latest
          EOF
